development:
  adapter:   postgresql
  encoding:  unicode
  database:  codemarks_server_backup
  pool: 5
  min_messages: warning

test: &TEST
  adapter:   postgresql
  encoding:  unicode
  database:  codemarks_test
  pool: 5
  min_messages: warning

production:
  adapter:   postgresql
  encoding:  unicode
  database:  codemarks_production
  pool: 5
  min_messages: warning

cucumber:
  <<: *TEST
